name: Auto Git Sync

on:
  push:
    branches:
      - main  # Executa sempre que houver alterações na branch main
  schedule:
    - cron: "*/10 * * * *"  # Executa a cada 10 minutos

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configurar usuário Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Atualizar repositório e sincronizar arquivos específicos
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git pull origin main --rebase
          git add main.py ClassPortfolio.py ClassStock.py ClassTransactions.py git_push.bat install_requirements.py utils.py
          git commit -m "Auto commit via GitHub Actions" || echo "Nada para commitar"
          git push https://$PAT_TOKEN@github.com/${{ github.repository }}.git main
