name: Auto Git Sync

on:
  push:
    branches:
      - dev  # Só escuta alterações na dev (não main!)
  schedule:
    - cron: "0 13 * * 1-5"  # Corre às 13:00 UTC (ex: antes do mercado americano)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar o main.py
        run: |
          python main.py
